apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: demo
data:
  DB_HOST: "host.minikube.internal"
  DB_NAME: "KubeCart_Orders"
  DB_USER: "kubecart_user"
  CATALOG_SERVICE_URL: "http://catalog-service.demo.svc.cluster.local"
